stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
    - raw_data_location
    - src/data_ingestion.py
    outs:
    - data_processed/raw
  data_validation:
    cmd: python src/data_validation.py
    deps:
    - data_processed/raw
    - src/data_validation.py
  data_preprocessing:
    cmd: python src/data_preprocessing.py
    deps:
    - data_processed/raw
    - src/data_preprocessing.py
    outs:
    - data_processed/cleaned
  feature_engineering:
    cmd: python src/feature_engineering.py
    deps:
    - data_processed/cleaned
    - src/feature_engineering.py
    outs:
    - data_processed/featured
  data_split_encode:
    cmd: python src/data_split_encode.py
    deps:
    - data_processed/featured
    - src/data_split_encode.py
    outs:
    - data_processed/dependency_split
  decision_tree:
    cmd: python src/dt.py
    deps:
    - data_processed/dependency_split
    - src/dt.py
    params:
    - decision_tree
    outs:
    - models/decision_tree
  random_forest:
    cmd: python src/rf.py
    deps:
    - data_processed/dependency_split
    - src/rf.py
    params:
    - random_forest
    outs:
    - models/random_forest
